export const metadata = {
  title: "BBMI Rankings – NCAA Football Ratings",
  description:
    "Live NCAA football rankings generated by the BBMI Football Model Index. Updated weekly with predictive performance metrics.",
  keywords: [
    "BBMI rankings",
    "NCAA football rankings",
    "college football ratings",
    "analytics",
    "football model",
    "SP+ ratings",
  ],
  openGraph: {
    title: "BBMI Rankings",
    description:
      "Advanced NCAA football rankings powered by the BBMI Football Model Index.",
    url: "https://bbmisports.com/ncaaf-rankings",
    siteName: "BBMI Sports",
    type: "website",
  },
};

export default function FootballRankingsLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
