export const metadata = {
  title: "WIAA Today’s Picks – Daily High School Predictions by BBMI",
  description:
    "Daily WIAA high school basketball picks generated by the Brantner Basketball Model Index. Data‑driven predictions updated throughout the season.",
  keywords: ["WIAA", "high school basketball", "model picks", "BBMI predictions"],
  openGraph: {
    title: "WIAA Today’s Picks – BBMI Predictions",
    description:
      "Daily WIAA basketball predictions powered by the Brantner Basketball Model Index.",
    url: "https://bbmihoops.com/wiaa-todays-picks",
    siteName: "BBMI Hoops",
  },
};

export default function WIAATodaysPicksLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}