export const metadata = {
  title: "Today's Game Lines – NCAA Baseball Predictions by BBMI",
  description:
    "Daily NCAA D1 baseball picks generated by the BBMI Poisson model. Run-line predictions with edge analysis, pitcher matchups, and live scores updated throughout the day.",
  keywords: [
    "baseball picks",
    "NCAA baseball predictions",
    "BBMI baseball",
    "college baseball betting",
    "NCAA baseball run line",
    "college baseball picks today",
  ],
  openGraph: {
    title: "Today's Game Lines – NCAA Baseball | BBMI Sports",
    description:
      "Daily NCAA D1 baseball predictions powered by the BBMI Poisson model. Run-line edges, pitcher matchups, and live scores.",
    url: "https://bbmisports.com/baseball/picks",
    siteName: "BBMI Sports",
  },
};

export default function BaseballPicksLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
