export const metadata = {
  title: "Baseball Picks – Daily NCAA Predictions by BBMI",
  description:
    "Daily NCAA D1 baseball picks generated by the BBMI Poisson model. Run-line, total, and moneyline predictions updated daily.",
  keywords: ["baseball picks", "NCAA baseball predictions", "BBMI baseball", "college baseball betting"],
  openGraph: {
    title: "Baseball Picks – BBMI Predictions",
    description: "Daily NCAA baseball predictions powered by BBMI.",
    url: "https://bbmisports.com/baseball/picks",
    siteName: "BBMI Sports",
  },
};

export default function BaseballPicksLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
