export const metadata = {
  title: "BBMI Rankings – Advanced NCAA Basketball Ratings",
  description:
    "Live NCAA basketball rankings generated by the Brantner Basketball Model Index. Updated daily with predictive performance metrics.",
  keywords: [
    "BBMI rankings",
    "NCAA rankings",
    "college basketball ratings",
    "analytics",
    "basketball model",
  ],
  openGraph: {
    title: "BBMI Rankings",
    description:
      "Advanced NCAA basketball rankings powered by the Brantner Basketball Model Index.",
    url: "https://bbmihoops.com/ncaa-rankings",
    siteName: "BBMI Hoops",
    type: "website",
  },
};

export default function RankingsLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}