"use client";

import { useState, useMemo, useEffect } from "react";
import Link from "next/link";
import rankingsData from "@/data/rankings/rankings.json";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import LogoBadge from "@/components/LogoBadge";
import NCAALogo from "@/components/NCAALogo";
import { ChevronUp, ChevronDown } from "lucide-react";

type Ranking = {
  team: string;
  conference: string;
  model_rank: number | string;
  kenpom_rank: number | string;
  net_ranking: number | string;
  last_ten: string;
  record: string;
};

export default function RankingsPage() {
  const [sortColumn, setSortColumn] = useState<keyof Ranking>("model_rank");
  const [sortDirection, setSortDirection] = useState<"asc" | "desc">("asc");
  const [search, setSearch] = useState("");
  const [conferenceFilter, setConferenceFilter] = useState("all");
  const [lastUpdated, setLastUpdated] = useState("");

  // JSON-LD injection
  useEffect(() => {
    const jsonLd = {
      "@context": "https://schema.org",
      "@type": "Dataset",
      name: "BBMI NCAA Basketball Rankings",
      description:
        "Live NCAA basketball rankings generated by the Brantner Basketball Model Index.",
      url: "https://bbmihoops.com/ncaa-rankings",
      dateModified: new Date().toISOString(),
    };

    const script = document.createElement("script");
    script.type = "application/ld+json";
    script.innerHTML = JSON.stringify(jsonLd);
    document.head.appendChild(script);

    return () => {
      document.head.removeChild(script);
    };
  }, []);

  // Last updated timestamp
  useEffect(() => {
    fetch("/data/rankings/last_updated.txt")
      .then((res) => {
        if (!res.ok) throw new Error("Bad response");
        return res.text();
      })
      .then((txt) => {
        if (txt.startsWith("<!DOCTYPE")) throw new Error("HTML returned");
        setLastUpdated(txt.trim());
      })
      .catch(() => setLastUpdated("Unknown"));
  }, []);

  // Normalize rankings
  const normalizedRankings = useMemo<Ranking[]>(() => {
    const raw = rankingsData as unknown;
    if (!Array.isArray(raw)) return [];

    const possibleTeamKeys = ["team", "Team", "name", "team_name", "teamName"];

    const parseNum = (v: unknown): number | string => {
      if (typeof v === "number") return v;
      if (typeof v === "string") {
        const n = Number(v.replace(/[^\d.-]/g, ""));
        return Number.isFinite(n) ? n : v;
      }
      return "";
    };

    return (raw as unknown[]).map((row): Ranking => {
      const r = row as Record<string, unknown>;

      let teamVal: unknown = "";
      for (const k of possibleTeamKeys) {
        if (k in r && r[k] != null && String(r[k]).trim() !== "") {
          teamVal = r[k];
          break;
        }
      }

      return {
        team: String(teamVal ?? ""),
        conference: String(r.conference ?? r.Conference ?? ""),
        model_rank: parseNum(r.model_rank ?? r.modelRank ?? r["Model Rank"]),
        kenpom_rank: parseNum(r.kenpom_rank ?? r.kenpomRank ?? r.kenpom),
        net_ranking: parseNum(r.net_ranking ?? r.netRanking ?? r.net),
        last_ten: String(r.last_ten ?? r.lastTen ?? ""),
        record: String(r.record ?? ""),
      };
    });
  }, []);

  const getRankTextColor = (value: number | string) => {
    const num = Number(value);
    if (isNaN(num)) return "font-mono text-stone-800";
    const ratio = Math.min(Math.max((num - 1) / 199, 0), 1);
    const r = Math.floor(255 * ratio);
    const g = Math.floor(180 * (1 - ratio) + 75 * ratio);
    return `font-mono text-[rgb(${r},${g},80)] font-medium tracking-tightest`;
  };

  const conferences = useMemo(() => {
    const set = new Set<string>();
    normalizedRankings.forEach((t) => set.add(t.conference));
    return Array.from(set).sort();
  }, [normalizedRankings]);

  const handleSort = (column: keyof Ranking) => {
    if (column === sortColumn) {
      setSortDirection((d) => (d === "asc" ? "desc" : "asc"));
    } else {
      setSortColumn(column);
      setSortDirection("asc");
    }
  };

  const sortIcon = (column: keyof Ranking) => {
    if (column !== sortColumn) return null;
    return sortDirection === "asc" ? (
      <ChevronUp className="inline-block w-4 h-4 ml-1 text-white" />
    ) : (
      <ChevronDown className="inline-block w-4 h-4 ml-1 text-white" />
    );
  };

  const filteredRankings = useMemo(() => {
    const q = search.toLowerCase();
    return normalizedRankings.filter((team) => {
      const matchesSearch =
        team.team.toLowerCase().includes(q) ||
        team.conference.toLowerCase().includes(q) ||
        String(team.model_rank).includes(q) ||
        String(team.kenpom_rank).includes(q) ||
        String(team.net_ranking).includes(q);

      const matchesConference =
        conferenceFilter === "all" || team.conference === conferenceFilter;

      return matchesSearch && matchesConference;
    });
  }, [search, conferenceFilter, normalizedRankings]);

  const sortedRankings = useMemo(() => {
    return [...filteredRankings].sort((a: Ranking, b: Ranking) => {
      const key = sortColumn;
      if (
        key === "model_rank" ||
        key === "kenpom_rank" ||
        key === "net_ranking"
      ) {
        const numA = Number(a[key]);
        const numB = Number(b[key]);
        if (!isNaN(numA) && !isNaN(numB)) {
          return sortDirection === "asc" ? numA - numB : numB - numA;
        }
      }
      const sa = String(a[key] ?? "");
      const sb = String(b[key] ?? "");
      return sortDirection === "asc"
        ? sa.localeCompare(sb)
        : sb.localeCompare(sa);
    });
  }, [filteredRankings, sortColumn, sortDirection]);

  const totalTeams = normalizedRankings.length;
  const visibleTeams = sortedRankings.length;

  return (
    <>
      <div className="section-wrapper">
        <div className="w-full max-w-[1600px] mx-auto px-4 sm:px-6 py-8">
          {/* HEADER */}
          <div className="mt-10 flex flex-col items-center mb-6">
            
            <h1 className="flex items-center text-2xl sm:text-3xl font-bold tracking-tightest leading-tight mt-2">
              <LogoBadge league="ncaa" className="h-8 mr-3" />
              <span>BBMI Men's Team Rankings</span>
            </h1>
          </div>

          {/* SEARCH + FILTERS */}
          <div className="mb-6 flex flex-col items-center gap-3">
            <Input
              placeholder="Search teams, conferences, rankings..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="h-9 w-64 text-sm tracking-tight"
            />

            <select
              value={conferenceFilter}
              onChange={(e) => setConferenceFilter(e.target.value)}
              className="h-9 w-48 text-sm tracking-tight rounded-md border border-stone-300 bg-white text-stone-900 px-2"
            >
              <option value="all">All conferences</option>
              {conferences.map((conf) => (
                <option key={conf} value={conf}>
                  {conf}
                </option>
              ))}
            </select>

            <Button
              variant="outline"
              className="h-9 w-32 text-sm tracking-tight"
              onClick={() => {
                setSearch("");
                setConferenceFilter("all");
                setSortColumn("model_rank");
                setSortDirection("asc");
              }}
            >
              Reset
            </Button>

            <div className="text-sm text-stone-600 tracking-tight">
              Showing <span className="font-semibold">{visibleTeams}</span> of{" "}
              <span className="font-semibold">{totalTeams}</span> teams. Updated{" "}
              {lastUpdated}
            </div>
          </div>

          {/* TABLE WRAPPER */}
          <div className="rankings-table mb-10 overflow-hidden border border-stone-200 rounded-md shadow-sm">
            <div className="rankings-scroll overflow-x-auto">
              <table className="min-w-[900px] w-full border-collapse">
                <thead>
                  <tr className="bg-[#0a1a2f] text-white text-sm">
                    <th
                      className="sticky left-0 z-30 cursor-pointer select-none px-3 py-2 text-left whitespace-nowrap bg-[#0a1a2f]"
                      style={{ width: 72 }}
                      onClick={() => handleSort("model_rank")}
                    >
                      BBMI Rank {sortIcon("model_rank")}
                    </th>
                    <th
                      className="sticky z-30 cursor-pointer select-none px-3 py-2 text-left whitespace-nowrap bg-[#0a1a2f]"
                      style={{ left: 72, width: 220 }}
                      onClick={() => handleSort("team")}
                    >
                      Team {sortIcon("team")}
                    </th>
                    <th
                      className="cursor-pointer select-none px-3 py-2 text-left whitespace-nowrap"
                      onClick={() => handleSort("conference")}
                    >
                      Conference {sortIcon("conference")}
                    </th>
                    <th
                      className="cursor-pointer select-none px-3 py-2 text-right whitespace-nowrap"
                      onClick={() => handleSort("kenpom_rank")}
                    >
                      KenPom {sortIcon("kenpom_rank")}
                    </th>
                    <th
                      className="cursor-pointer select-none px-3 py-2 text-right whitespace-nowrap"
                      onClick={() => handleSort("net_ranking")}
                    >
                      NET {sortIcon("net_ranking")}
                    </th>
                    <th
                      className="cursor-pointer select-none px-3 py-2 text-right whitespace-nowrap"
                      onClick={() => handleSort("record")}
                    >
                      Record {sortIcon("record")}
                    </th>
                  </tr>
                </thead>

                <tbody>
                  {sortedRankings.map((team) => (
                    <tr
                      key={`${team.team}-${team.model_rank}`}
                      className="bg-white border-b border-stone-200 text-sm"
                    >
                      <td
                        className="sticky left-0 z-20 bg-white px-3 py-2 font-mono text-sm whitespace-nowrap"
                        style={{ width: 72 }}
                      >
                        {team.model_rank}
                      </td>
                      <td
                        className="sticky z-20 bg-white px-3 py-2 font-medium text-stone-900 whitespace-nowrap"
                        style={{ left: 72, width: 220 }}
                      >
                        <Link
                          href={`/ncaa-team/${encodeURIComponent(team.team)}`}
                          className="hover:underline cursor-pointer flex items-center gap-2"
                        >
                          <NCAALogo teamName={team.team} size={28} />
                          <span>{team.team}</span>
                        </Link>
                      </td>
                      <td className="px-3 py-2 whitespace-nowrap text-stone-700">
                        {team.conference}
                      </td>
                      <td className="px-3 py-2 whitespace-nowrap text-right">
                        <span className={getRankTextColor(team.kenpom_rank)}>
                          {team.kenpom_rank}
                        </span>
                      </td>
                      <td className="px-3 py-2 whitespace-nowrap text-right">
                        <span className={getRankTextColor(team.net_ranking)}>
                          {team.net_ranking}
                        </span>
                      </td>
                      <td className="px-3 py-2 whitespace-nowrap text-right font-mono text-sm text-stone-700">
                        {team.record || "—"}
                      </td>
                    </tr>
                  ))}

                  {sortedRankings.length === 0 && (
                    <tr>
                      <td
                        colSpan={6}
                        className="text-center py-6 text-stone-500"
                      >
                        No teams match your filters.
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </div>

        </div>
      </div>
    </>
  );
}
