"use client";

import React, { useState, useEffect, useMemo } from "react";
import Link from "next/link";
import NCAALogo from "@/components/NCAALogo";
import seedingData from "@/data/seeding/seeding.json";
import { collection, getDocs } from "firebase/firestore";
import { db } from "@/app/firebase-config";
import { useAuth } from "@/app/AuthContext";

// ── Types ─────────────────────────────────────────────────────────────────────

type Team = {
  name: string;
  seed: number;
  region: string;
};

type BracketEntry = {
  userId: string;
  bracketName: string;
  email: string;
  picks: Record<string, string>;
  complete: boolean;
  updatedAt: unknown;
};

// ── Scoring ───────────────────────────────────────────────────────────────────

const ROUND_NAMES = ["Round of 64", "Round of 32", "Sweet 16", "Elite 8", "Final Four", "Championship"];
const ROUND_POINTS = [10, 20, 40, 80, 160, 320];
const ROUND_PREFIXES = ["R64|", "R32|", "S16|", "E8|", "F4|", "CHAMP|"];

// Tournament results — auto-generated by the pipeline
// Format: { "R64|East|0": "Duke", "R64|East|1": "TCU", ... }
// Falls back to empty object if file doesn't exist yet
import tournamentResultsRaw from "@/data/seeding/tournament-results.json";
const ACTUAL_RESULTS: Record<string, string> = tournamentResultsRaw as Record<string, string>;

function scoreEntry(picks: Record<string, string>): {
  total: number;
  byRound: number[];
  correct: number;
  possible: number;
} {
  const byRound = ROUND_PREFIXES.map((prefix, ri) => {
    let roundScore = 0;
    Object.entries(picks).forEach(([key, team]) => {
      if (!key.startsWith(prefix)) return;
      const actual = ACTUAL_RESULTS[key];
      if (actual && actual === team) {
        roundScore += ROUND_POINTS[ri];
      }
    });
    return roundScore;
  });

  const total = byRound.reduce((s, v) => s + v, 0);
  const correct = Object.entries(picks).filter(([key, team]) => ACTUAL_RESULTS[key] === team).length;

  // Max possible: current score + points for all undecided games where the picked team is still alive
  // Simplified: current score + remaining round points for unpicked/undecided games
  const decidedKeys = new Set(Object.keys(ACTUAL_RESULTS));
  let possible = total;
  Object.entries(picks).forEach(([key, _team]) => {
    if (decidedKeys.has(key)) return;
    const ri = ROUND_PREFIXES.findIndex(p => key.startsWith(p));
    if (ri >= 0) possible += ROUND_POINTS[ri];
  });

  return { total, byRound, correct, possible };
}

// ── Main Page ─────────────────────────────────────────────────────────────────

export default function LeaderboardPage() {
  const { user } = useAuth();
  const [entries, setEntries] = useState<BracketEntry[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedUserId, setSelectedUserId] = useState<string | null>(null);

  const allTeams: Team[] = useMemo(() => {
    if (!Array.isArray(seedingData)) return [];
    return (seedingData as Record<string, unknown>[]).map(r => ({
      name:   String(r.Team ?? r.team ?? ""),
      seed:   Number(r.CurrentSeed ?? r.currentSeed ?? r.Seed ?? 0),
      region: String(r.Region ?? r.region ?? ""),
    }));
  }, []);

  // Load all brackets
  useEffect(() => {
    (async () => {
      try {
        const snap = await getDocs(collection(db, "bracketChallenge"));
        const data: BracketEntry[] = [];
        snap.forEach(doc => {
          data.push(doc.data() as BracketEntry);
        });
        setEntries(data);
      } catch (e) {
        console.error("Failed to load leaderboard:", e);
      } finally {
        setLoading(false);
      }
    })();
  }, []);

  // Score and rank entries
  const ranked = useMemo(() => {
    return entries
      .map(entry => ({
        ...entry,
        score: scoreEntry(entry.picks),
      }))
      .sort((a, b) => b.score.total - a.score.total || b.score.possible - a.score.possible);
  }, [entries]);

  const selectedEntry = selectedUserId ? ranked.find(e => e.userId === selectedUserId) : null;

  const hasResults = Object.keys(ACTUAL_RESULTS).length > 0;

  const TH: React.CSSProperties = {
    backgroundColor: "#0a1a2f", color: "#ffffff",
    padding: "8px 12px", fontSize: 10.5, fontWeight: 700,
    textTransform: "uppercase", letterSpacing: "0.06em", textAlign: "center",
    whiteSpace: "nowrap",
  };
  const TD: React.CSSProperties = {
    padding: "8px 12px", fontSize: 13, borderTop: "1px solid #f0f0ef",
    textAlign: "center", verticalAlign: "middle",
  };

  if (loading) {
    return <div style={{ textAlign: "center", padding: 60, color: "#94a3b8" }}>Loading leaderboard...</div>;
  }

  return (
    <div className="section-wrapper">
      <div className="w-full max-w-[1000px] mx-auto px-4 sm:px-6 py-8">

        <div style={{ marginTop: 40, display: "flex", flexDirection: "column", alignItems: "center", marginBottom: 24 }}>
          <h1 style={{ fontSize: "1.875rem", fontWeight: 800, letterSpacing: "-0.02em" }}>
            🏆 Bracket Challenge Leaderboard
          </h1>
          <p style={{ color: "#78716c", fontSize: 14, textAlign: "center", maxWidth: 500, marginTop: 8 }}>
            {ranked.length} bracket{ranked.length !== 1 ? "s" : ""} submitted.
            {hasResults ? " Scores update as games are completed." : " Scores will populate once games begin."}
          </p>
          <Link href="/bracket-challenge" style={{
            marginTop: 10, fontSize: 13, color: "#2563eb", fontWeight: 600, textDecoration: "none",
          }}>
            ← Edit your bracket
          </Link>
        </div>

        {/* Standings table */}
        {ranked.length > 0 && (
          <div style={{
            border: "1px solid #e7e5e4", borderRadius: 10, overflow: "hidden",
            backgroundColor: "#fff", boxShadow: "0 1px 4px rgba(0,0,0,0.06)", marginBottom: 32,
          }}>
            <div style={{ overflowX: "auto" }}>
              <table style={{ borderCollapse: "collapse", width: "100%", minWidth: 600 }}>
                <thead>
                  <tr>
                    <th style={{ ...TH, width: 50 }}>#</th>
                    <th style={{ ...TH, textAlign: "left" }}>Bracket</th>
                    <th style={TH}>Picks</th>
                    {hasResults && (
                      <>
                        <th style={TH}>Score</th>
                        <th style={TH}>Correct</th>
                        <th style={TH}>Max Possible</th>
                      </>
                    )}
                    <th style={TH}>Champion Pick</th>
                    <th style={{ ...TH, width: 80 }}>View</th>
                  </tr>
                </thead>
                <tbody>
                  {ranked.map((entry, i) => {
                    const champPick = entry.picks["CHAMP|Final|0"];
                    const champTeam = champPick ? allTeams.find(t => t.name === champPick) : undefined;
                    const isMe = user?.uid === entry.userId;
                    const totalPicks = Object.keys(entry.picks).length;
                    return (
                      <tr key={entry.userId} style={{
                        backgroundColor: isMe ? "rgba(59,130,246,0.06)" : i % 2 === 0 ? "#fafaf9" : "#fff",
                      }}>
                        <td style={{ ...TD, fontWeight: 700, color: i < 3 ? "#b45309" : "#57534e" }}>
                          {i === 0 ? "🥇" : i === 1 ? "🥈" : i === 2 ? "🥉" : i + 1}
                        </td>
                        <td style={{ ...TD, textAlign: "left", fontWeight: isMe ? 700 : 500 }}>
                          {entry.bracketName || "Anonymous"}
                          {isMe && <span style={{ fontSize: 10, color: "#3b82f6", marginLeft: 6 }}>(you)</span>}
                        </td>
                        <td style={TD}>{totalPicks}</td>
                        {hasResults && (
                          <>
                            <td style={{ ...TD, fontWeight: 700, color: "#0a1a2f", fontSize: 15 }}>{entry.score.total}</td>
                            <td style={TD}>{entry.score.correct}</td>
                            <td style={{ ...TD, color: "#64748b" }}>{entry.score.possible}</td>
                          </>
                        )}
                        <td style={TD}>
                          {champTeam ? (
                            <div style={{ display: "flex", alignItems: "center", gap: 4, justifyContent: "center" }}>
                              <NCAALogo teamName={champTeam.name} size={16} />
                              <span style={{ fontSize: 12, fontWeight: 600 }}>{champTeam.seed} {champTeam.name}</span>
                            </div>
                          ) : <span style={{ color: "#a8a29e" }}>—</span>}
                        </td>
                        <td style={TD}>
                          <button
                            onClick={() => setSelectedUserId(selectedUserId === entry.userId ? null : entry.userId)}
                            style={{
                              fontSize: 11, fontWeight: 600, color: "#3b82f6", background: "none",
                              border: "1px solid #bfdbfe", borderRadius: 4, padding: "2px 8px", cursor: "pointer",
                            }}
                          >
                            {selectedUserId === entry.userId ? "Hide" : "View"}
                          </button>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {ranked.length === 0 && (
          <div style={{ textAlign: "center", padding: 48, color: "#94a3b8", fontStyle: "italic" }}>
            No brackets submitted yet. <Link href="/bracket-challenge" style={{ color: "#3b82f6" }}>Be the first!</Link>
          </div>
        )}

        {/* Selected bracket detail */}
        {selectedEntry && (
          <div style={{
            border: "1px solid #e7e5e4", borderRadius: 10, overflow: "hidden",
            backgroundColor: "#fff", marginBottom: 32, boxShadow: "0 1px 4px rgba(0,0,0,0.06)",
          }}>
            <div style={{
              background: "linear-gradient(90deg, #0a1628 0%, #1e3a5f 100%)",
              color: "#fff", padding: "12px 18px", fontWeight: 700,
            }}>
              {selectedEntry.bracketName}&apos;s Picks
            </div>
            <div style={{ padding: "16px 20px", maxHeight: 400, overflowY: "auto" }}>
              {Object.entries(selectedEntry.picks)
                .sort(([a], [b]) => a.localeCompare(b))
                .map(([key, team]) => {
                  const actual = ACTUAL_RESULTS[key];
                  const isCorrect = actual && actual === team;
                  const isWrong = actual && actual !== team;
                  return (
                    <div key={key} style={{
                      display: "flex", justifyContent: "space-between", alignItems: "center",
                      padding: "4px 8px", fontSize: 12, borderBottom: "1px solid #f5f5f4",
                      backgroundColor: isCorrect ? "rgba(22,163,74,0.06)" : isWrong ? "rgba(220,38,38,0.04)" : "transparent",
                    }}>
                      <span style={{ color: "#78716c", fontFamily: "ui-monospace, monospace", fontSize: 11 }}>{key}</span>
                      <div style={{ display: "flex", alignItems: "center", gap: 4 }}>
                        <NCAALogo teamName={team} size={14} />
                        <span style={{ fontWeight: 600, color: isCorrect ? "#16a34a" : isWrong ? "#dc2626" : "#0a1a2f" }}>
                          {team}
                        </span>
                        {isCorrect && <span style={{ color: "#16a34a", fontSize: 10 }}>✓</span>}
                        {isWrong && <span style={{ color: "#dc2626", fontSize: 10 }}>✗</span>}
                      </div>
                    </div>
                  );
                })}
            </div>
          </div>
        )}

        {/* Scoring breakdown */}
        <div style={{
          maxWidth: 400, margin: "0 auto 40px",
          backgroundColor: "#f0f9ff", border: "1px solid #bae6fd",
          borderRadius: 10, padding: "16px 20px",
        }}>
          <div style={{ fontSize: 14, fontWeight: 700, color: "#0c4a6e", marginBottom: 8 }}>📊 Scoring System</div>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 4, fontSize: 13, color: "#0369a1" }}>
            {ROUND_NAMES.map((name, i) => (
              <React.Fragment key={name}>
                <span>{name}</span>
                <span style={{ fontWeight: 700, textAlign: "right" }}>{ROUND_POINTS[i]} pts</span>
              </React.Fragment>
            ))}
          </div>
        </div>

      </div>
    </div>
  );
}
