export const metadata = {
  title: "Model Picks – Daily NCAA Predictions by BBMI",
  description:
    "Daily NCAA basketball picks generated by the Brantner Basketball Model Index. Data‑driven predictions updated throughout the season.",
  keywords: ["model picks", "NCAA predictions", "BBMI picks"],
  openGraph: {
    title: "Model Picks – BBMI Predictions",
    description:
      "Daily NCAA basketball predictions powered by BBMI.",
    url: "https://bbmihoops.com/model-picks",
    siteName: "BBMI Hoops",
  },
};


export default function NCAATodaysPicksLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}